### ISSUE TITLE
Not sure what's causing this error message

### ISSUE THREAD

**Issue by EvanZ** [aaronn/django-rest-framework-passwordless#1]
`{"detail":"Unable to email you a login code. Try again later."}%`

**Comment by aaronn** [comment]
Do you have a smtp server running locally or remotely?

**Comment by chachra** [comment]
If console backend is set it should just work with no smtp server.... I'm getting the same error. Some logs or relevant error would be great!

**Comment by chachra** [comment]
I think I found the issue. Not setting `PASSWORDLESS_EMAIL_NOREPLY_ADDRESS` will cause this error @EvanZ

**Comment by EvanZ** [comment]
@chachra Several months later...still getting the same error message even after your suggestion.

**Comment by tchandler** [comment]
@EvanZ I ran into a similar issue, `PASSWORDLESS_EMAIL_NOREPLY_ADDRESS` has to be set _within_ the `PASSWORDLESS_AUTH` setting:
```python
PASSWORDLESS_AUTH = {
    'PASSWORDLESS_AUTH_TYPES': ['EMAIL', 'MOBILE'],
    'PASSWORDLESS_EMAIL_NOREPLY_ADDRESS': 'noreply@test.test'
}
```

**Comment by EvanZ** [comment]
Hmmm...ok, I'll see if I can get that to work!

**Comment by aaronn** [comment]
Yeah, make sure you have a `PASSWORDLESS_EMAIL_NOREPLY_ADDRESS` set and have some kind of SMTP server hooked up.

**Comment by aaronsnig501** [comment]
@aaronn This issue still seems to exist. I have set the `PASSWORDLESS_EMAIL_NOREPLY_ADDRESS` but I'm receiving this error. My code was working fine last night, but today it has stopped and I have no idea why. There's no additional way of finding out any more information about this.

I don't know if maybe it is something wrong with my code, my environment (env variables are set, but maybe there's something else), maybe it's an issue with Gmail, or an issue with the package. But the error messages are being swallowed so I don't know how to continue debugging this and it's blocking further development.

There's no point in only providing error messages to end users because if anything goes wrong then developers have no way of tracking down the issue
